import os
import logging
from typing import Optional
from dotenv import load_dotenv

load_dotenv()

logger = logging.getLogger(__name__)


def get_env_var(name: str, default: Optional[str] = None, required: bool = False) -> Optional[str]:
    """Retrieve an environment variable.

    Args:
        name: The name of the environment variable.
        default: Default value if the variable is not set.
        required: If True and the variable is not set (and no default), raise ValueError.

    Returns:
        The value of the environment variable, or default/None.

    Raises:
        ValueError: If required=True and the variable is missing with no default.
    """
    val = os.getenv(name, default)
    if required and not val:
        raise ValueError(f"Required environment variable '{name}' is not set.")
    return val


# --- API Keys ---
ANTHROPIC_API_KEY: Optional[str] = get_env_var("ANTHROPIC_API_KEY")
OPENAI_API_KEY: Optional[str] = get_env_var("OPENAI_API_KEY")
SUPABASE_URL: Optional[str] = get_env_var("SUPABASE_URL")
SUPABASE_KEY: Optional[str] = get_env_var("SUPABASE_KEY")
ELEVENLABS_API_KEY: Optional[str] = get_env_var("ELEVENLABS_API_KEY")
PICOVOICE_ACCESS_KEY: Optional[str] = get_env_var("PICOVOICE_ACCESS_KEY")
GEMINI_API_KEY: Optional[str] = get_env_var("GEMINI_API_KEY")
GLM_API_KEY: Optional[str] = get_env_var("GLM_API_KEY")

# Friday Security — API token for authenticating all /api/* routes.
# If FRIDAY_API_TOKEN is empty AND we are NOT in an explicitly-marked dev
# environment (FRIDAY_DEV_MODE=1), a random token is auto-generated on
# first run and written back to .env so subsequent starts reuse it.
# Set FRIDAY_DEV_MODE=1 to explicitly opt into the unauthenticated dev mode
# (NEVER use this in production).
FRIDAY_API_TOKEN: Optional[str] = get_env_var("FRIDAY_API_TOKEN")
FRIDAY_DEV_MODE: bool = get_env_var("FRIDAY_DEV_MODE", default="0") == "1"


def _ensure_api_token() -> str:
    """Return a non-empty API token, auto-generating + persisting if needed.

    Security model:
      - If FRIDAY_API_TOKEN is already set in env → use it.
      - Else if FRIDAY_DEV_MODE=1 → return empty string (dev mode, no auth).
      - Else → auto-generate a 32-byte random token, write to .env, return it.
    """
    import secrets
    import os as _os
    from pathlib import Path

    existing = _os.getenv("FRIDAY_API_TOKEN")
    if existing:
        return existing

    if _os.getenv("FRIDAY_DEV_MODE", "0") == "1":
        return ""  # explicit dev mode

    # Auto-generate
    new_token = secrets.token_urlsafe(32)
    env_path = Path(".env")
    line = f"FRIDAY_API_TOKEN={new_token}\n"
    if env_path.exists():
        # Append (don't overwrite existing content)
        with open(env_path, "a") as f:
            f.write("\n# Auto-generated by Friday on first start\n")
            f.write(line)
    else:
        with open(env_path, "w") as f:
            f.write(line)
    _os.environ["FRIDAY_API_TOKEN"] = new_token
    logger.info(
        "FRIDAY_API_TOKEN auto-generated and saved to .env. "
        "Set FRIDAY_DEV_MODE=1 only for local development without auth."
    )
    return new_token


# Eagerly ensure the token exists at import time so the app refuses to start
# unauthenticated unless explicitly in dev mode.
FRIDAY_API_TOKEN = _ensure_api_token()

# New integrations
OPENWEATHERMAP_API_KEY: Optional[str] = get_env_var("OPENWEATHERMAP_API_KEY")
SPOTIFY_CLIENT_ID: Optional[str] = get_env_var("SPOTIFY_CLIENT_ID")
SPOTIFY_CLIENT_SECRET: Optional[str] = get_env_var("SPOTIFY_CLIENT_SECRET")
HOME_ASSISTANT_TOKEN: Optional[str] = get_env_var("HOME_ASSISTANT_TOKEN")

# --- Brain Provider ---
# Determines which LLM provider to use: "glm" (default, free), "claude", "gemini", or "ollama"
BRAIN_PROVIDER: str = get_env_var("BRAIN_PROVIDER", default="glm")

# --- Autonomy Profile ---
# Controls what Friday can do without user approval.
# GUEST:    Everything requires approval.
# STANDARD: Read-only auto-approves, destructive requires approval.
# POWER:    PC/Browser auto-approves, file deletion requires approval.
AUTONOMY_PROFILE: str = get_env_var("AUTONOMY_PROFILE", default="GUEST")

# --- Web Search ---
TAVILY_API_KEY: Optional[str] = get_env_var("TAVILY_API_KEY")

# --- Logging ---
LOG_LEVEL: str = get_env_var("LOG_LEVEL", default="INFO")
LOG_FILE: str = "friday.log"

# --- Workspace (lazy creation) ---
WORKSPACE_ROOT: str = os.path.join(os.getcwd(), "friday_workspace")


def ensure_workspace() -> str:
    """Lazily create the workspace root directory if it doesn't exist.

    Returns:
        The path to the workspace root.
    """
    if not os.path.exists(WORKSPACE_ROOT):
        os.makedirs(WORKSPACE_ROOT, exist_ok=True)
        logger.info(f"Created workspace root: {WORKSPACE_ROOT}")
    return WORKSPACE_ROOT
