"""Shared authentication utilities for the FRIDAY API.

This module provides ``require_auth`` — a FastAPI dependency that
validates the Bearer token (``FRIDAY_API_TOKEN``) on protected
endpoints. It mirrors the logic in ``api.main.verify_token`` but is
extracted into a reusable module so that individual route files can
apply it per-endpoint (e.g. protecting ``/api/health/deep`` while
leaving ``/api/health`` and ``/api/ping`` open for liveness probes).

Security model
--------------
- If ``FRIDAY_DEV_MODE=1`` is set AND ``FRIDAY_API_TOKEN`` is empty →
  no auth (local dev only). A warning is logged on first use.
- Otherwise ``FRIDAY_API_TOKEN`` is required (auto-generated by
  ``config.settings._ensure_api_token`` on first run if missing).
- Accepts the token via the ``Authorization: Bearer <token>`` header
  (preferred) or the ``?token=<token>`` query parameter (fallback for
  ``EventSource`` / SSE, which cannot send custom headers).
- All comparisons use ``hmac.compare_digest`` (timing-safe).

Usage
-----
.. code-block:: python

    from fastapi import Depends
    from core.auth import require_auth

    @router.get("/deep")
    async def deep_health(_auth: str = Depends(require_auth)) -> dict:
        ...
"""
from __future__ import annotations

import hmac
import logging
from typing import Optional

from fastapi import Depends, HTTPException, Request, status
from fastapi.security import HTTPAuthorizationCredentials, HTTPBearer

# Reuse the existing auto-generated token from config.settings — this
# keeps a single source of truth and preserves the dev-mode short-circuit
# that the rest of the API already relies on.
from config.settings import FRIDAY_API_TOKEN, FRIDAY_DEV_MODE

logger = logging.getLogger(__name__)

# auto_error=False so we can return a clean 401 instead of FastAPI's
# default 403 "Not authenticated" — and so we can fall back to the
# ?token=<...> query parameter before rejecting.
_bearer_scheme = HTTPBearer(auto_error=False)

# Track whether we have already warned about running in dev mode
# (avoids log spam on every request).
_DEV_MODE_WARNED: bool = False


async def require_auth(
    request: Request,
    credentials: Optional[HTTPAuthorizationCredentials] = Depends(_bearer_scheme),
) -> str:
    """FastAPI dependency: require a valid Bearer token.

    Returns the validated token string on success (so endpoint handlers
    can use it for audit logging if they want). Raises ``HTTPException``
    with status 401 on failure.

    The 401 (Unauthorized) status is used instead of 403 (Forbidden)
    because this dependency gates *authentication*, not *authorization*:
    a missing/invalid token means "we don't know who you are", which is
    semantically a 401.
    """
    global _DEV_MODE_WARNED

    # Dev-mode short-circuit: explicit opt-in for unauthenticated local dev.
    # Only fires when FRIDAY_DEV_MODE=1 AND no token is configured — if a
    # token IS configured, we enforce it even in dev mode (so operators
    # can test auth flows without flipping dev mode off).
    if FRIDAY_DEV_MODE and not FRIDAY_API_TOKEN:
        if not _DEV_MODE_WARNED:
            logger.warning(
                "FRIDAY_DEV_MODE=1 with no FRIDAY_API_TOKEN — "
                "authentication DISABLED. This is for local development "
                "only; NEVER enable in production."
            )
            _DEV_MODE_WARNED = True
        return "dev_token"

    # 1. Authorization: Bearer <token> header (preferred)
    if credentials and credentials.credentials:
        if hmac.compare_digest(credentials.credentials, FRIDAY_API_TOKEN):
            return credentials.credentials

    # 2. ?token=<token> query parameter (fallback for EventSource / SSE,
    #    which cannot set custom headers)
    qp_token = request.query_params.get("token")
    if qp_token and hmac.compare_digest(qp_token, FRIDAY_API_TOKEN):
        return qp_token

    # 3. Reject — no valid credential found
    raise HTTPException(
        status_code=status.HTTP_401_UNAUTHORIZED,
        detail=(
            "Authentication required. Provide a valid Bearer token via "
            "the Authorization header (or ?token=... query parameter). "
            "Set FRIDAY_API_TOKEN env var, or FRIDAY_DEV_MODE=1 for "
            "local development only."
        ),
        headers={"WWW-Authenticate": "Bearer"},
    )


def is_auth_required() -> bool:
    """Return True if auth is currently required (i.e., not in dev mode)."""
    return not (FRIDAY_DEV_MODE and not FRIDAY_API_TOKEN)


__all__ = ["require_auth", "is_auth_required"]
