import logging
from collections import Counter
from typing import Any, Dict, List, Optional

from database.vector_store import VectorStore

logger = logging.getLogger(__name__)


class SubconsciousMind:
    """Surfaces relevant patterns from stored memories without a direct query.

    The subconscious mind works by:
    1. Pulling a broad set of memories related to the current context.
    2. Clustering them by category / metadata tags.
    3. Identifying dominant patterns and surfacing them as "intuitions".
    """

    def __init__(self, vector_store: Optional[VectorStore] = None) -> None:
        try:
            self.vector_store = vector_store or VectorStore()
        except Exception as exc:
            logger.warning(f"VectorStore init failed, using None: {exc}")
            self.vector_store = None  # type: ignore[assignment]
        self.active_patterns: List[str] = []
        self._last_context: Optional[str] = None
        self._pattern_scores: Dict[str, float] = {}

    def surface_patterns(self, current_context: str) -> List[str]:
        """Surface subconscious patterns relevant to *current_context*.

        Returns a list of dominant pattern/category strings.
        """
        self._last_context = current_context

        if self.vector_store is None:
            logger.debug("surface_patterns: vector_store is None, returning [].")
            return []

        try:
            # Broad search to find clusters of relevant memories
            memories = self.vector_store.search(current_context, top_k=20)
        except Exception as exc:
            logger.error(f"surface_patterns search failed: {exc}")
            return []

        if not memories:
            self.active_patterns = []
            return []

        # --- Real pattern clustering ---
        # 1. Extract categories and tags from metadata
        categories: List[str] = []
        tags: List[str] = []
        for m in memories:
            meta = m.get("metadata", {})
            if isinstance(meta, dict):
                cat = meta.get("category")
                if cat:
                    categories.append(str(cat))
                meta_tags = meta.get("tags", [])
                if isinstance(meta_tags, list):
                    tags.extend(str(t) for t in meta_tags)

        # 2. Count frequency to find dominant patterns
        cat_counter = Counter(categories)
        tag_counter = Counter(tags)

        # 3. Score patterns: categories get 2× weight, tags 1×
        scored: Dict[str, float] = {}
        for cat, count in cat_counter.items():
            scored[cat] = scored.get(cat, 0) + count * 2.0
        for tag, count in tag_counter.items():
            scored[tag] = scored.get(tag, 0) + count * 1.0

        # 4. Keep patterns that appear more than once or have a score ≥ 2
        dominant = [p for p, s in scored.items() if s >= 2.0]
        # If nothing is dominant, take the top-3 by score
        if not dominant and scored:
            dominant = [p for p, _ in sorted(scored.items(), key=lambda x: -x[1])[:3]]

        self.active_patterns = dominant
        self._pattern_scores = scored
        logger.debug(f"Surfaced patterns: {dominant}")
        return dominant

    def get_intuition(self) -> str:
        """Return an intuition string based on the currently active patterns.

        The intuition is generated by examining which patterns are dominant
        and producing a contextual suggestion.
        """
        if not self.active_patterns:
            return "System intuition: Neutral. No strong patterns detected."

        # Prioritized pattern-based intuition generation
        high_priority_keywords = {"High Priority", "urgent", "critical", "important"}
        warning_keywords = {"warning", "error", "failure", "issue", "bug"}
        creative_keywords = {"creative", "design", "brainstorm", "idea"}

        active_set = set(self.active_patterns)

        if active_set & high_priority_keywords:
            return (
                "I have a strong intuition that we should prioritize the current task "
                "given past results. Several high-priority patterns have surfaced."
            )

        if active_set & warning_keywords:
            return (
                "I sense caution is warranted. Warning patterns have surfaced from "
                "past experiences that may be relevant here."
            )

        if active_set & creative_keywords:
            return (
                "Creative patterns are surfacing — this might be a good moment for "
                "brainstorming or exploring new ideas."
            )

        # Generic: list top patterns
        top_patterns = sorted(
            self.active_patterns,
            key=lambda p: self._pattern_scores.get(p, 0),
            reverse=True,
        )[:3]
        pattern_str = ", ".join(top_patterns)
        return f"System intuition: Active patterns detected ({pattern_str}). Proceed with awareness."

    def get_pattern_scores(self) -> Dict[str, float]:
        """Return the scored patterns from the last surface_patterns call."""
        return dict(self._pattern_scores)
